version: 2
project_name: kubectl-unmount
release:
  github:
    owner: dancavallaro
    name: kubectl-unmount
builds:
  - id: kubectl-unmount
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    env:
      - CGO_ENABLED=0
    main: cmd/plugin/main.go
archives:
  - id: kubectl-unmount
    name_template: "{{ .ProjectName }}_v{{.Version}}_{{ .Os }}_{{ .Arch }}"
